### ISSUE TITLE
Idea to create T2 Wind Turbine with a multi block structure

### ISSUE THREAD

**Issue by genestrashcan** [eln2/eln2#126]
i got the idea we can use to make the t2 wind turbine eventually after seeing and playing immersive engineering and immersive petroleum which you use many blocks to build a structure and then right click it with a wrench and it turns into a large model that makes up multiple blocks.

Now here's my idea for the Tier 2 Wind Turbine, you build it by placing multiple blocks in a formation that would look something like a turbine similar to structures built in immersive engineering.

My suggestion is the t2 turbine tower should be 50 blocks high and the blades 25 - 30 blocks long each. when all the correct blocks are placed correctly you right click it with a wrench and the blocks are replaced with a animated model like builds in immersive engineering. The t2 turbine should be double the height of the t2 powerline transmission tower since that's what they are most of the time in real life.

the T2 turbine should produce around a average of 15Kw at around 3200v to be balanced to ELN (In Real Life these things produce around 2-3 Megawatts each on average).

a photo to give you a idea how big one of these things should be.

![500-foot-wind-turbine](https://user-images.githubusercontent.com/11165643/111534250-28f81080-873e-11eb-9b5d-a55676221380.jpg)

**Comment by jrddunbr** [comment]
Too early to tell what this is going to look like, but this is not Eln1 and we're not copying stuff over from the old mod so the balance here is kinda irrelevant. Shelving for later discussion.
