### ISSUE TITLE
Add option to mod cfg file to disable wind turbine sound

### ISSUE THREAD

**Issue by genestrashcan** [eln2/eln2#129]
Please add a option to the mod cfg file of eln2 to disable wind turbine sounds, in real life turbines don't make any whoosh whoosh blade chopping air sound at all except a hum from the generator unless their big.

that "Whoosh Whoosh Whoosh Whoosh Whoosh Whoosh" sound that comes from the t1 wind turbine when it reaches full speed can get really annoying when you have a lot of them around.

**Comment by jrddunbr** [comment]
Irrelevant to Eln2.
