### ISSUE TITLE
Advanced cable creation

### ISSUE THREAD

**Issue by Welbre** [eln2/eln2#130]
Hi, i have a ideia to the cables in [Single Cable #52](https://github.com/eln2/eln2/issues/52).

Well, my ideia is create customizable cables, diferent from eln 1.7.10 cables,but like real cables, this cables have 2 main parts, the insulation and the core.

The insulation cover the core that have the conductor material, isolating the core.
can created with some many material, as rubber, plastic or wood(maybe), and can be thicker for more insulation.
The core is where the electrical energy can travel, have resistance but little amount.
this core can be created with a single copper cables or others material, and you can use how many single cables you want, to get a most maximum high current in the cable.

The big difference between eln and eln2 cables, will be that you can modify the cables properties:
--The insulation can insulate a maximum voltage in the core.
--You can place a cable without insulation.
--The cable current limite can be expanded.
--The cable resistance can be modified using different material or many single cables to be created.

The cable not explode any more, but can take damages.
--The insulation can be half impaired, due temperatue.
--If the cable is very hot(because the joule effect), the insulation melt, and tha cable will be without the insulation.
--The cables melt too if then get a very high temperature.

The non-insulated cables:
--them will got damage in the player if the player touch the cable or if the player has close to the cable(to high voltage).
--The cables half insulated, this cable too will give electric shock, but less strong.
--cables will lost energy to the ground because the potential difference.

Crafting this cable:
We can create this new cable in two ways:

Using the Crafting Table, we can create a single cables:
https://imgur.com/a/dPtJBvQ
and create a most thicker cable:
https://imgur.com/a/sfEB3mJ

Using a new machine(wire maker) we can craft the cables:
https://imgur.com/a/HCGHhWx

some exemplo cable:
https://imgur.com/a/Cq4F3wn

The nominal temperature is the temperature of the cable will get stable with 12A.

I hope you like it and implement my idea, any doubts can talk to me.

**Comment by jrddunbr** [comment]
So actually, we have plans very similar to this that we've been planning for a while.

I'll put it out bluntly - I really dislike the crafting table for several reasons.

I'd much rather have a cable making machine. Effectively, at the 12V tier, you can basically just extrude some copper at the right temperature on an anvil or something to make a crude cable and get work done, but once you're past that stage, you would make a wire roller and a insulation bath. At lower voltages, insulation isn't really important as you don't need to protect the player, but it's very important for later tiers (and if you want your cables to be able to be colored and stuff like that).

A lot of the current documentation we have for this is in the [Electrical Age Google Drive](https://drive.google.com/drive/folders/1rWXCEy9EQmKbeYGKnJssirRZnXX0fHkj?usp=sharing).

**Comment by jrddunbr** [comment]
I'm going to close this because it's honestly a duplicate.
