### ISSUE TITLE
Solar powered pole mounted outdoor light

### ISSUE THREAD

**Issue by genestrashcan** [eln2/eln2#134]
i also had the idea to add a solar powered dusk to dawn light based upon the real solar powered variant of the LED dusk to dawn light which has been created by electrical engineers in the last few years. This variant is a full solar powered LED variant of the original 175w mercury vapor dusk to dawn light.

the photo below shows you one, it's a light with a panel attached to it on the pole. I installed one of these solar variants on a barn about a year ago and it's quite bright.

![61xK1U4ma6L _AC_SL1500_](https://user-images.githubusercontent.com/11165643/120897624-1e3e7080-c5f5-11eb-9c52-a8ab7fc9533c.jpg)

**Comment by jrddunbr** [comment]
Duplicate
