### ISSUE TITLE
General observations

### ISSUE THREAD

**Issue by Caeleron** [eln2/eln2#161]
Work in progress. Posting this now so that people can start looking at it, since this will take a bit.

- CellBockBase
  - [ ] https://github.com/age-series/ElectricalAge2/blob/bf5d03f7919b0ca09ad6726378fb9ed4530e636f/src/main/java/org/eln2/mc/common/blocks/CellBlockBase.kt#L52 None of these arguments appear to ever be null when digging inside of Minecraft.
  - [ ] https://github.com/age-series/ElectricalAge2/blob/bf5d03f7919b0ca09ad6726378fb9ed4530e636f/src/main/java/org/eln2/mc/common/blocks/CellBlockBase.kt#L57 Ditto
  - [ ] https://github.com/age-series/ElectricalAge2/blob/bf5d03f7919b0ca09ad6726378fb9ed4530e636f/src/main/java/org/eln2/mc/common/blocks/CellBlockBase.kt#L69 This name collides with a similar function in Block which is called by Minecraft if `onDestroyedByPlayer` returns true, and also includes the Block's BlockState in the argument. 
  - [ ] https://github.com/age-series/ElectricalAge2/blob/bf5d03f7919b0ca09ad6726378fb9ed4530e636f/src/main/java/org/eln2/mc/common/blocks/CellBlockBase.kt#L70 I verified that this function does get called in both the client and the server. I would invert this conditional and move the code inside of it. 
  - [ ] https://github.com/age-series/ElectricalAge2/blob/bf5d03f7919b0ca09ad6726378fb9ed4530e636f/src/main/java/org/eln2/mc/common/blocks/CellBlockBase.kt#L83 This branch is never taken since the annotation says that this should always run in the server. `world?.isClientSide` should always be false. In addition, `world`, `pos`, and `neighbor` should never be null.

**Comment by jrddunbr** [comment]
> [Line 52](https://github.com/age-series/ElectricalAge2/blob/bf5d03f7919b0ca09ad6726378fb9ed4530e636f/src/main/java/org/eln2/mc/common/blocks/CellBlockBase.kt#L52) None of these arguments appear to ever be null when digging inside of Minecraft.

So... this is probably a good chance to talk about this, but technically because it's a Java code thing, I treat it as external code that could be unsafe. Unless it has the not null annotation on it, might be best to stick with these safer function definitions.
