### ISSUE TITLE
1x1 Solar Panel

### ISSUE THREAD

**Issue by jrddunbr** [eln2/eln2#180]
12V 1x1 solar panel. Solar panels top out at 150 watts per square meter, so since this isn't adjustable let's make it 100 watts max.

- [ ] Solar panel has postive and negative sides and can be chained
- [ ] model
- [ ] texture
- [ ] dimished solar performance with different angles of the sun that are not directly overhead

No rotation or other mechanics required, this will be handled in issues like #127 #118  and possibly others.

**Comment by JeffersonTan** [comment]
[solar_panel_1x1.zip](https://github.com/age-series/ElectricalAge2/files/8102600/solar_panel_1x1.zip)
Here's a solar panel model + texture I've made, hopefully it fits the description -Marcus Lee

**Comment by jrddunbr** [comment]
Just need a texture for a solar panel now based on the model.

Then the code needs to be written.

**Comment by jrddunbr** [comment]
Still need a texture for the device, and it will need to have some backing code written, right now I have it written as a voltage source in #186

**Comment by jrddunbr** [comment]
The model for the solar panel needs to be rotated 90 degrees in the blockstate.

**Comment by jrddunbr** [comment]
I have Knight20k making the updated solar panel texture. Needed some changes to the texture (smaller border, more accurate cell texture, etc.)
