### ISSUE TITLE
Clean workspace before builds?

### ISSUE THREAD

**Issue by jrddunbr** [eln2/eln2#19]
So I see a lot of `UP TO DATE` in our current CI output. I'm wondering if it's caching build artifacts on our self-hosted CI server.

I would like to propose that we add `./gradlew clean` in the following task:

https://github.com/eln2/eln2/blob/6d9e5885ad5701387a19f3838bcff015a9623fcf/.github/workflows/ci.yml#L28-L29

On the plus side, we don't constantly download the Gradle binaries every run on self-hosted, so doing the self-hosted will still be faster than using the public GitHub actions minutes we're granted as an org.

It would appear that full compiles of the code take 40-60 seconds, but when we were running on GitHub actions public servers we were taking sometimes over 120 seconds.

**Comment by Baughn** [comment]
It's definitely caching artifacts, but adding a clean won't prevent that; you need to erase (or disable) the central Gradle cache instaed. See settings.kts for how to do that.

**Comment by jrddunbr** [comment]
I think that the current system is working well for our needs and doesn't need changing. Currently, builds run faster than Codacy, so timing is even more of a non-issue.
