### ISSUE TITLE
Error: Electrical age 2 (eln2) has failed to load correctly ...

### ISSUE THREAD

**Issue by powderedd** [eln2/eln2#206]
java.lang.RuntimeException: java.lang.NoClassDefFoundError:  
[error log](https://pastebin.com/dHAGMXV5)

**Comment by powderedd** [comment]
Other info:  
i am using windows 10
i have no mods other than eln2 and Kotlin for Forge

**Comment by jrddunbr** [comment]
Yeah it's just straight up broken so I am just going to delete the release. Feel free to throw together the development environment and try fixing it.

**Comment by powderedd** [comment]
how would i set up a dev enviroment? ive only built a mod once, and it wasnt made with kotlin.

**Comment by jrddunbr** [comment]
Same as any other Forge development environment. Clone down the repository, run `gradlew.exe build` and then `gradlew.exe runClient`. (on mac/linux do `./gradlew build` then `./gradlew runClient`)

**Comment by powderedd** [comment]
do i need to have java jdk or kotlin installed?

**Comment by jrddunbr** [comment]
You will need the most recent JDK. Kotlin is automatically fetched.

**Comment by jrddunbr** [comment]
Follow basically any YouTube Forge tutorial for 1.18

**Comment by powderedd** [comment]
i built it myself and it still gives the error

**Comment by jrddunbr** [comment]
Yeah, it needs to be fixed. Just building it yourself won't fix it.

Good luck.
