### ISSUE TITLE
Experimental Power Source 1 - Zero Point Energy

### ISSUE THREAD

**Issue by EllingtonElectrician** [eln2/eln2#97]
I had a idea for some experimental power sources that could be created in both creative and survival.

The first one is a Zero Point Energy type Electrical generator. To get in it survival you need to find rare materials from both the end and nether and build a beacon to act as the power source which is only part of the recipe, It also needs a zero point control board made from rare materials that is used to control and limit how much energy it can put out. 

Once all the rare materials are found and it has been built it can be configured to set the precise voltage it produces and also set the max amperage it can produce. This should replace the creative only energy / power source item that was only limited to setting voltage in older versions of E.A.

**Comment by jrddunbr** [comment]
What do you mean by "Zero Point Energy"? Do you mean a creative source? What is a "zero point control board"?

**Comment by Electricianfromhell** [comment]
Zero Point means it doesn't need any source of fuel like fossil fuels or even wind or solar, huge amounts of energy are pretty much generated from NOTHING.

**Comment by Caeleron** [comment]
In ELN we had voltage sources exist as just that, voltage sources. We're probably going to do the same thing for ELN2. Of course they will still be only accessible from Creative. Having current sources exist in a similar manner for ELN2 would help for debugging and educational purposes.

**Comment by jrddunbr** [comment]
We will also have power sources and power sinks and that will be mostly creative. I'm amicable to having a super duper endgame thing like that but it would be a timed operation instead of free power 24/7. Otherwise, it's super OP and not suitable for survival mode.

**Comment by jrddunbr** [comment]
This isn't happening.
