### ISSUE TITLE
Neutrino Powered Solar Panels

### ISSUE THREAD

**Issue by EllingtonElectrician** [eln2/eln2#98]
this article shows that Neutrino power solar panels are probably coming to the electrical industry in the future...

[Neutrino Powered Solar Cells](https://powerpulse.net/neutrinovoltaic-technology-solar-cells-that-dont-need-light/)

My second idea for a experimental energy sources is a Neutrino Powered Solar Panel. It is powered by neutrinos coming in from outerspace any time of day, So it works at night too. A Rotating version will need a special neutrino solar tracker which will make it still face the sun during the day since the sun is the strongest source of neutrinos. At night the neutrino solar tracker will make it tilt towards the middle of the sky since neutrinos come from space too. It produces near the same amount of power as regular solar panels and can stack voltage in series and amperage in parallel like regular solar panels and batteries. It also doesn't need batteries since neutrinos coming in from space power it even at night. 

To build these in survival you would need to find rare materials not found easily in survival.

**Comment by jrddunbr** [comment]
@Caeleron -

I want a reality check on this. I can find no evidence of the science besides two or three random news articles that makes it look like they are desperately looking for funding and have nothing to show for as far as actual science is concerned. Yes, neutrinos exist, but I can find no evidence in academic papers that they are of any use to us to collect, besides studying the sun.

**Comment by Caeleron** [comment]
Neutrinos are notorious for interacting with pretty much nothing. Detecting them requires a lot of fancy physics on its own. Harvesting them for energy is out of the question.
